schema_version = "1.0.0"

id = "add_frame_range_presets"
version = "1.1.1"
name = "Add Frame Range Presets"
tagline = "Create preset frame ranges in just a click"
maintainer = "Jay Friesen <jaymfriesen@outlook.com>"
type = "add-on"

website = "https://github.com/stoatsnhoney/add-frame-range-presets-blender-addon"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
   "2024 Jay Friesen",
]
